# Generated by Django 3.2.12 on 2023-08-14 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersquestions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='software',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.softwarecategory'),
        ),
        migrations.AddField(
            model_name='featuressoftware',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.software'),
        ),
        migrations.AddField(
            model_name='cart',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.software'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
